### ISSUE TITLE
Incorrect scroll offset.

### ISSUE THREAD

**Issue by uplusion23** [AhsanE/backdrop-polyfill-chrome#1]
On my personal website, I've manually added an object to test this implementation, and although it works, the offset is off from the original scroll position, as seen here [in this image](https://i.imgur.com/GFPRdQM.png)

The element was appended to my page via developer tools with the html below.
`<div id="filter" style="display:block;position:fixed;top:0;left:0;width:100%;height:200px;z-index:9999;margin:0;padding:0;border:1px solid red;box-sizing:border-box;"></div>`

Then the script was ran to apply the changes and append the iframe inside that div.

I was able to remedy the issue using a manual dirty fix to take the backdropapply element's offsetHeight and multiplying that by two, and subtracting that to the scroll offset.
```
var scroll = this.scrollY
var scrollx = this.scrollX
scroll = scroll - (backdropapply.offsetHeight * 2);
```

**Comment by ahsane** [comment]
Alright, I'll test it out. BTW, can you link me to your page with the example?

**Comment by ahsane** [comment]
Closing. Re-open if it is not fixed.
